name: ecommerce01
description: Mobile Ecommerce Application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  country_code_picker: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: KumbhSans
      fonts:
        - asset: fonts/KumbhSans-Regular.ttf
